config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get  '/signup',    to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users



  resources :spaces, only: [:index, :show]

  namespace :host do
    resources :spaces, only: [:new, :create, :edit, :update, :destroy]
  end

  post '/spaces/filter', to: 'spaces#filter'
  post '/spaces/:id/review', to: 'space_ratings#create'
  post '/spaces', to: 'spaces#index'
  post 'spaces/:id/book', to: "bookings#create"
  # resources :spaces
  resources :space_ratings, only: :update
  resources :charges

end

app/models/user.rb
class User < ApplicationRecord
  has_many :spaces, foreign_key: :owner_id
  has_many :bookings, foreign_key: :renter_id

  before_save { self.email = email.downcase }
  validates :first_name, :last_name, :birthday, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "Account created!"
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your changes have been updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :host, :birthday, :phone_number, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless @user == current_user
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="form-row md-form">
    <div class="form-group col-md-6 md-form">
      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name, :class => "form-control" %>
    </div>
    <div class="form-group col-md-6 md-form">
      <%= f.label :last_name, "Last Name" %>
      <%= f.text_field :last_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group md-form">
    <%= f.label :email, "Email" %>
    <%= f.email_field :email, :class => "form-control" %>
  </div>
  <div class="form-row md-form">
    <div class="form-group col-md-6 md-form">
      <%= f.label :birthday, "Birthday" %>
      <%= f.date_field :birthday, :class => "form-control" %>
    </div>
    <div class="form-group col-md-6 md-form">
      <%= f.label :phone_number, "Phone Number" %>
      <%= f.text_field :phone_number, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group md-form">
    <%= f.label :password, "Password" %>
    <%= f.password_field :password, :class => "form-control" %>
  </div>
  <div class="form-group md-form">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, :class => "form-control" %>
  </div>
  <div class="form-group text-center">
    <%= f.submit yield(:button_text), :class => "btn btn-primary" %>
             <hr class="hr-light mb-3 mt-4">
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row flex-center pt-5 mt-3">
	<div class="col-md-6 col-xl-5 mx-auto">
		<div class="card">
			<div class="card-body">
				<div class="text-center">
					<h3 class="white-text"><i class="fa fa-space white-text"></i> Edit Profile</h3>
					<hr>
				</div>
				<% provide(:title, 'Edit profile') %>
				<% provide(:button_text, 'Update') %>
				<%= render "form" %>
				<% if @user == current_user %>
				<p>Remove your account? <%= link_to "Delete", @user, method: :delete,
					data: { confirm: "Are you sure?" } %></p>
					<% end %>
				</div>
			</div>
		</div>
	</div>

app/views/users/index.html.erb
<div class="main-content container">  <h1>All Users</h1>
    <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.first_name + " " + user.last_name, user %></li>
    <% end %>
    </ul>
</div>

app/views/users/new.html.erb
<div class="row flex-center pt-5 mt-3">
	<div class="col-md-6 col-xl-5 mx-auto">
		<div class="card">
			<div class="card-body">
				<div class="text-center">
					<h3 class="white-text"><i class="fa fa-space white-text"></i> Sign up</h3>
					<hr>
				</div>
				<% provide(:title, 'Register') %>
				<% provide(:button_text, 'Create my account') %>
				<%= render "form" %>
			</div>
		</div>
	</div>
</div>

app/views/users/old_show.erb
<div class="main-content container">
  <% provide(:title, @user) %>
  <div>
    <h1><%= @user.first_name + " " + @user.last_name %></h1>
    <div>
    <p><%= link_to "Post a space", new_host_space_path %></p>
      <% if @user.spaces.any? %>
      <h2> My spaces for rent: </h2>
        <ul>
          <% @user.spaces.each do | space | %>
            <li> <%= link_to space.title, space %></li>
            <%= image_tag space.space_image.url(:thumb) %>
            <p><%= link_to "Edit", edit_host_space_path(:space => space.id)
             %></p>
          <% end %>
        </ul>
    <% end %>
    </div>
    <div>
      <% if @user.bookings.any? %>
      <h2> My bookings: </h2>
        <ul>
          <% @user.bookings.each do | booking | %>
            <li> <%= link_to booking.space.title, booking.space %></li>
            <%= image_tag booking.space.space_image.url(:thumb) %>
          <% end %>
        </ul>
    <% end %>
    <p><%= link_to "Settings", edit_user_path(current_user) %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- <div class="main-content container"> -->
  <section class="bg-primary rentals-section" id="about">
    <div class="container">
      <% provide(:title, @user) %>
      <div>
        <h1 id="profile-name"><%= @user.first_name + " " + @user.last_name %></h1>
        <div>
          <p><%= link_to "Settings", edit_user_path(current_user), :class => "text-white" %></p>
        </div>
      </section>
      <section class="bg-white rentals-section" id="about">
        <div class="container">
          <h2> My spaces for rent </h2>
          <% if @user.spaces.any? %>
          <div class="row my-rentals">
            <% @user.spaces.each do | space | %>
              <div class="col-lg-3 text-center mb-4" id="profile-space-card">
              <%= link_to image_tag(space.space_image.url(:square)), space_path(:id => space.id), :class => "rounded-circle img-fluid d-block mx-auto" %>
              <hr>
              <h3><%= link_to space.title, space %></h3>
              <p><%= space.location %></p>
              <small><%= link_to "Edit", edit_host_space_path(:space => space.id), :class => "btn btn-primary btn-sm"
              %></small>
              </div>
            <% end %>
          <% else %>
            <p>You currently have no rentals.</p>            
          <% end %>
          </div>
        </div>
      </section>

  <section class="bg-white rentals-section" id="about">
    <div class="container">
      <h2> My bookings </h2>
      <% if @user.bookings.any? %>
        <div class="row my-rentals">
        <% @user.bookings.each do | booking | %>
          <% if booking.renter != booking.space.owner %>
            <div class="col-lg-3 text-center mb-4" id="profile-space-card">
              <%= link_to image_tag(booking.space.space_image.url(:square)), space_path(:id => booking.space.id), :class => "rounded-circle img-fluid d-block mx-auto" %>
              <hr>
              <h3><%= link_to booking.space.title, booking.space %></h3>
              <p><%= booking.space.location %></p>
              <%#=binding.pry%>
              <p><%= booking.start_time.strftime("Booked on %m/%d/%Y at %I:%M%p") %></p>
            </div>
          <%end%>
        <% end %>
      <% else %>
        <p>You currently have no bookings.</p>
      <% end %>
      </div>
    </div>
  </div>
</div>
</section>