config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get  '/signup',    to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users



  resources :spaces, only: [:index, :show]

  namespace :host do
    resources :spaces, only: [:new, :create, :edit, :update, :destroy]
  end

  post '/spaces/filter', to: 'spaces#filter'
  post '/spaces/:id/review', to: 'space_ratings#create'
  post '/spaces', to: 'spaces#index'
  post 'spaces/:id/book', to: "bookings#create"
  # resources :spaces
  resources :space_ratings, only: :update
  resources :charges

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

   def index
   	 render :index
   end

end

app/views/home/_about_us.html.erb
    <section class="p-0" id="portfolio">
    <!-- Page Content -->
    <div class="container">

      <!-- Introduction Row -->
      <br><br>
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Meet the Team</h2>
        <hr class="my-4">
      </div><br>
      <!-- Team Members Row -->
      <div class="row">
        <div class="col-sm-4 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto our-photos" src="https://avatars3.githubusercontent.com/u/26559263?s=460&v=4" alt="">
          <h3>Noah Krell
            <br><small>Developer</small>
          </h3>
          <p>
            <a href="https://github.com/noahkrell"><i class="fa fa-github social-icon" aria-hidden="true"></i></a>
            &nbsp<a href="https://www.linkedin.com/in/noah-krell-042a2a43/"><i class="fa fa-linkedin-square social-icon" aria-hidden="true"></i></a>
            &nbsp<a href="mailto:noahkrell14@gmail.com"><i class="fa fa-envelope social-icon" aria-hidden="true"></i></a>
          </p>
        </div>
        <div class="col-sm-4 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto our-photos" src="https://avatars0.githubusercontent.com/u/16946850?s=460&v=4" alt="">
          <h3>Peter Haley
            <br><small>Developer</small>
          </h3>
          <p>
            <a href="https://github.com/pblhaley"><i class="fa fa-github social-icon" aria-hidden="true"></i></a>
            &nbsp<a href="https://www.linkedin.com/in/pblhaley/"><i class="fa fa-linkedin-square social-icon" aria-hidden="true"></i></a>
            &nbsp<a href="mailto:pblhaley@gmail.com"><i class="fa fa-envelope social-icon" aria-hidden="true"></i></a>
          </p>
        </div>
        <div class="col-sm-4 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto our-photos" src="https://media.licdn.com/dms/image/C5103AQEfRjUONctlDg/profile-displayphoto-shrink_800_800/0?e=1529337600&v=beta&t=reimEp0QwQ6VSIVEUUulxrBJK9SENe2k9K2PyHlN2ds" alt="">
          <h3>Catherine Valek
            <br><small>Developer</small>
          </h3>
          <p>
            <a href="https://github.com/catherinevalek"><i class="fa fa-github social-icon" aria-hidden="true"></i></a>
            &nbsp<a href="https://www.linkedin.com/in/catherinevalek/"><i class="fa fa-linkedin-square social-icon" aria-hidden="true"></i></a>
            &nbsp<a href="mailto:catherine.valek@gmail.com"><i class="fa fa-envelope social-icon" aria-hidden="true"></i></a>
          </p>
        </div>
      </div>
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Space App 2017</p>
      </div>
      <!-- /.container -->
    </footer>
    </section>

app/views/home/_section.html.erb
 <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">How We Work</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fa fa-4x fa-map-marker text-primary mb-3 sr-icons"></i>
              <h3 class="mb-3">Find Your Space</h3>
              <p class="text-muted mb-0">Use the search bar above to find open spaces near you.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fa fa-4x fa-credit-card text-primary mb-3 sr-icons"></i>
              <h3 class="mb-3">Book Securely</h3>
              <p class="text-muted mb-0">We accept all major cards in addition to web and mobile apps through Stripe.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fa fa-4x fa-code-fork text-primary mb-3 sr-icons"></i>
              <h3 class="mb-3">Do Work</h3>
              <p class="text-muted mb-0">Working alone, or with a group, just show up, plug in, and get to work!</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fa fa-4x fa-home text-primary mb-3 sr-icons"></i>
              <h3 class="mb-3">Host Your Space</h3>
              <p class="text-muted mb-0">Want to turn that empty office into cash? Sign up to host your space today!</p>
            </div>
          </div>
        </div>
      </div>
    </section>

app/views/home/index.html.erb
<header class="masthead text-center text-white d-flex">
  <div class="container my-auto">
    <div class="row home-search-content">
      <div class="col-lg-10 mx-auto">
        <h1 class="text-uppercase">
          <strong>Space.</strong>
        </h1>
        <!-- <hr> -->
      </div>
      <div class="col-lg-8 mx-auto">
        <p class="text-faded mb-5", id="home-tagline">Find a workspace near you.</p>

        <div class="featurette">
          <div class="featurette-inner text-center">
           <%= form_tag(spaces_path, :method => "post", class: "search") do %>
           <div class="input-group input-group-lg">
             <%= text_field_tag :search, params[:search], placeholder: "Enter a location (ex. 'Austin')", class: "form-control"%>
             <span class="input-group-btn">
               <%= submit_tag "Search", :name => nil, style: "display:inline;", class: "btn btn-danger", id: "home-search-btn" %>
             </span>
           </div>
           <% end %>
         </div>
       </div>
     </div>
   </div>
 </div>
</div>
</header>
<%= render "section"%>
<%= render "about_us"%>