config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get  '/signup',    to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users



  resources :spaces, only: [:index, :show]

  namespace :host do
    resources :spaces, only: [:new, :create, :edit, :update, :destroy]
  end

  post '/spaces/filter', to: 'spaces#filter'
  post '/spaces/:id/review', to: 'space_ratings#create'
  post '/spaces', to: 'spaces#index'
  post 'spaces/:id/book', to: "bookings#create"
  # resources :spaces
  resources :space_ratings, only: :update
  resources :charges

end

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
  <div class="container">
    <%= link_to "Space.", root_path, :class=>"navbar-brand js-scroll-trigger" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if logged_in? %>
<!--         <li class="dropdown">
          <a class="dropdown-toggle nav-link" data-toggle="dropdown" href="#"><%=current_user.first_name%>
            <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%#= link_to "Profile", current_user %>
              </li>
              <li>
              <%#= link_to "Settings", edit_user_path(current_user)%>

              </li>
              <li>
               <%#= link_to "Log out", logout_path, method: "delete"%>

              </li>
            </ul>
          </li> -->
          <li class="nav-item">
            <%= link_to current_user.first_name, current_user, :class=>"nav-link js-scroll-trigger" %>
          </li>
          <li class="nav-item">
            <%= link_to "Post a Space", new_host_space_path, :class=>"nav-link js-scroll-trigger" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", logout_path, method: "delete", :class=>"nav-link js-scroll-trigger" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Log in", login_path, :class=>"nav-link js-scroll-trigger" %>
          </li>
          <li class="nav-item">
            <%= link_to "Register", signup_path, :class=>"nav-link js-scroll-trigger" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SpaceApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>

  
  </head>


  <header>
    <%= render "layouts/header" %>
    
  </header>

  <body>
    <div class= "container">
        <% if flash[:success] %>

      <div class="alert alert-info">
        <%= flash[:success] %>
      </div>
    <% end %>

    <% if flash[:danger] %>
      <div class="alert alert-danger">
        <%= flash[:danger] %>
      </div>
    <% end %>
  </div>
    <%= yield %>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>